In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
print ("Basic setup complete")

Basic setup complete


In [2]:
df_train = pd.read_csv("dataset/train.csv")
df_sample = pd.read_csv("dataset/sample_submission.csv")
df_test = pd.read_csv("dataset/test.csv")
df_train.head()

Patient Id  Patient Age Genes in mother's side Inherited from father  \
0  PID0x6418          2.0                    Yes                    No   
1  PID0x25d5          4.0                    Yes                   Yes   
2  PID0x4a82          6.0                    Yes                    No   
3  PID0x4ac8         12.0                    Yes                    No   
4  PID0x1bf7         11.0                    Yes                    No   

  Maternal gene Paternal gene  Blood cell count (mcL) Patient First Name  \
0           Yes            No                4.760603            Richard   
1            No            No                4.910669               Mike   
2            No            No                4.893297           Kimberly   
3           Yes            No                4.705280            Jeffery   
4           NaN           Yes                4.720703            Johanna   

  Family Name Father's name  ...  Birth defects  \
0         NaN         Larre  ...            NaN   
1         NaN        Brycen  ...       Multiple   
2         NaN        Nashon  ...       Singular   
3   Hoelscher        Aayaan  ...       Singular   
4    Stutzman         Suave  ...       Multiple   

   White Blood cell count (thousand per microliter) Blood test result  \
0                                          9.857562               NaN   
1                                          5.522560            normal   
2                                               NaN            normal   
3                                          7.919321      inconclusive   
4                                          4.098210               NaN   

  Symptom 1 Symptom 2 Symptom 3 Symptom 4  Symptom 5  \
0       1.0       1.0       1.0       1.0        1.0   
1       1.0       NaN       1.0       1.0        0.0   
2       0.0       1.0       1.0       1.0        1.0   
3       0.0       0.0       1.0       0.0        0.0   
4       0.0       0.0       0.0       0.0        NaN   

                               Genetic Disorder  \
0   Mitochondrial genetic inheritance disorders   
1                                           NaN   
2  Multifactorial genetic inheritance disorders   
3   Mitochondrial genetic inheritance disorders   
4  Multifactorial genetic inheritance disorders   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
1                      Cystic fibrosis  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer  

[5 rows x 45 columns]

In [3]:
df_train.columns

Index(['Patient Id', 'Patient Age', 'Genes in mother's side',
       'Inherited from father', 'Maternal gene', 'Paternal gene',
       'Blood cell count (mcL)', 'Patient First Name', 'Family Name',
       'Father's name', 'Mother's age', 'Father's age', 'Institute Name',
       'Location of Institute', 'Status', 'Respiratory Rate (breaths/min)',
       'Heart Rate (rates/min', 'Test 1', 'Test 2', 'Test 3', 'Test 4',
       'Test 5', 'Parental consent', 'Follow-up', 'Gender', 'Birth asphyxia',
       'Autopsy shows birth defect (if applicable)', 'Place of birth',
       'Folic acid details (peri-conceptional)',
       'H/O serious maternal illness', 'H/O radiation exposure (x-ray)',
       'H/O substance abuse', 'Assisted conception IVF/ART',
       'History of anomalies in previous pregnancies',
       'No. of previous abortion', 'Birth defects',
       'White Blood cell count (thousand per microliter)', 'Blood test result',
       'Symptom 1', 'Symptom 2', 'Symptom 3', 'Symptom 4', 'S

In [4]:
df_sample.head()

Patient Id                              Genetic Disorder  \
0  PID0x6418   Mitochondrial genetic inheritance disorders   
1  PID0x25d5              Single-gene inheritance diseases   
2  PID0x4a82  Multifactorial genetic inheritance disorders   
3  PID0x4ac8   Mitochondrial genetic inheritance disorders   
4  PID0x1bf7  Multifactorial genetic inheritance disorders   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
1                      Cystic fibrosis  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer

In [5]:
df_test.head()

Patient Id  Patient Age Genes in mother's side Inherited from father  \
0  PID0x4175            6                     No                   Yes   
1  PID0x21f5           10                    Yes                    No   
2  PID0x49b8            5                     No                   NaN   
3  PID0x2d97           13                     No                   Yes   
4  PID0x58da            5                     No                   NaN   

  Maternal gene Paternal gene  Blood cell count (mcL) Patient First Name  \
0            No            No                4.981655            Charles   
1           NaN           Yes                5.118890          Catherine   
2            No            No                4.876204              James   
3           Yes            No                4.687767              Brian   
4           NaN           Yes                5.152362               Gary   

  Family Name Father's name  ...  \
0         NaN          Kore  ...   
1         NaN        Homero  ...   
2         NaN       Danield  ...   
3         NaN       Orville  ...   
4         NaN        Issiah  ...   

   History of anomalies in previous pregnancies  No. of previous abortion  \
0                                           -99                         2   
1                                           Yes                       -99   
2                                            No                         0   
3                                           Yes                       -99   
4                                            No                       -99   

  Birth defects White Blood cell count (thousand per microliter)  \
0      Multiple                                       -99.000000   
1      Multiple                                         8.179584   
2      Singular                                       -99.000000   
3      Singular                                         6.884071   
4      Multiple                                         6.195178   

   Blood test result Symptom 1 Symptom 2  Symptom 3  Symptom 4  Symptom 5  
0  slightly abnormal      True      True       True       True       True  
1             normal     False     False      False       True      False  
2  slightly abnormal     False     False       True       True      False  
3             normal      True     False       True      False       True  
4             normal      True      True       True       True      False  

[5 rows x 43 columns]

In [21]:
print(df_train["Genetic Disorder"].describe())
print("\n******************************\n")
print(df_train["Genetic Disorder"].unique())

count                                           19937
unique                                              3
top       Mitochondrial genetic inheritance disorders
freq                                            10202
Name: Genetic Disorder, dtype: object

******************************

['Mitochondrial genetic inheritance disorders' nan
 'Multifactorial genetic inheritance disorders'
 'Single-gene inheritance diseases']


In [20]:
print(df_train["Disorder Subclass"].describe())
print("\n**********************************\n")
print(df_train["Disorder Subclass"].unique())

count              19915
unique                 9
top       Leigh syndrome
freq                5160
Name: Disorder Subclass, dtype: object

**********************************

["Leber's hereditary optic neuropathy" 'Cystic fibrosis' 'Diabetes'
 'Leigh syndrome' 'Cancer' 'Tay-Sachs' 'Hemochromatosis'
 'Mitochondrial myopathy' nan "Alzheimer's"]


In [26]:
print (df_train["Genetic Disorder"].isna().sum())
print (df_train["Disorder Subclass"].isna().sum())
print (df_train.shape)

2146
2168
(22083, 45)


In [27]:
df_train.isna().sum()

Patient Id                                             0
Patient Age                                         1427
Genes in mother's side                                 0
Inherited from father                                306
Maternal gene                                       2810
Paternal gene                                          0
Blood cell count (mcL)                                 0
Patient First Name                                     0
Family Name                                         9691
Father's name                                          0
Mother's age                                        6036
Father's age                                        5986
Institute Name                                      5106
Location of Institute                                  0
Status                                                 0
Respiratory Rate (breaths/min)                      2149
Heart Rate (rates/min                               2113
Test 1                         

In [37]:
temp = df_train[df_train["Genetic Disorder"].isna()]
temp.head()

Patient Id  Patient Age Genes in mother's side Inherited from father  \
1   PID0x25d5          4.0                    Yes                   Yes   
13   PID0xc25          0.0                    Yes                    No   
52  PID0x264c          0.0                    Yes                    No   
68  PID0x20e7          8.0                    Yes                    No   
75  PID0x2447          2.0                    Yes                   Yes   

   Maternal gene Paternal gene  Blood cell count (mcL) Patient First Name  \
1             No            No                4.910669               Mike   
13            No           Yes                4.807778               Adam   
52           Yes            No                4.921015              James   
68           NaN           Yes                5.259736             Warner   
75           Yes           Yes                4.927532            Michele   

   Family Name Father's name  ...  Birth defects  \
1          NaN        Brycen  ...       Multiple   
13         NaN          Tong  ...       Multiple   
52       Tracy        Romolo  ...       Singular   
68      Shumay       Laramie  ...            NaN   
75         NaN        Raudel  ...       Singular   

    White Blood cell count (thousand per microliter)  Blood test result  \
1                                           5.522560             normal   
13                                          8.440593           abnormal   
52                                               NaN  slightly abnormal   
68                                          9.719873  slightly abnormal   
75                                          5.169576           abnormal   

   Symptom 1 Symptom 2 Symptom 3 Symptom 4  Symptom 5  Genetic Disorder  \
1        1.0       NaN       1.0       1.0        0.0               NaN   
13       0.0       1.0       1.0       0.0        0.0               NaN   
52       NaN       0.0       0.0       0.0        0.0               NaN   
68       1.0       0.0       1.0       0.0        0.0               NaN   
75       1.0       1.0       0.0       0.0        1.0               NaN   

         Disorder Subclass  
1          Cystic fibrosis  
13          Leigh syndrome  
52               Tay-Sachs  
68  Mitochondrial myopathy  
75         Cystic fibrosis  

[5 rows x 45 columns]

In [38]:
df_train_copy = df_train.copy()

In [44]:
df_train.dropna(how = "any", inplace = True)
df_train.shape

(6706, 45)

Only **30% data** is left 

In [45]:
df_train.isna().sum()

Patient Id                                          0
Patient Age                                         0
Genes in mother's side                              0
Inherited from father                               0
Maternal gene                                       0
Paternal gene                                       0
Blood cell count (mcL)                              0
Patient First Name                                  0
Family Name                                         0
Father's name                                       0
Mother's age                                        0
Father's age                                        0
Institute Name                                      0
Location of Institute                               0
Status                                              0
Respiratory Rate (breaths/min)                      0
Heart Rate (rates/min                               0
Test 1                                              0
Test 2                      

In [51]:
df_train.head()

Patient Id  Patient Age Genes in mother's side Inherited from father  \
8   PID0x8ce3         11.0                     No                    No   
9   PID0x8660          4.0                     No                   Yes   
12  PID0x74ab          1.0                    Yes                   Yes   
14  PID0x7678          6.0                    Yes                    No   
18  PID0x952d         10.0                    Yes                   Yes   

   Maternal gene Paternal gene  Blood cell count (mcL) Patient First Name  \
8            Yes            No                5.209058             Willie   
9            Yes           Yes                4.752272               John   
12            No            No                4.612265               Eric   
14           Yes            No                4.620420               Ruth   
18           Yes            No                4.751452              James   

   Family Name Father's name  ...  Birth defects  \
8      Camacho            Tr  ...       Multiple   
9     Sandoval       Gregori  ...       Multiple   
12     Harness          Mano  ...       Singular   
14       Homza       Cesareo  ...       Multiple   
18     Whipple          Dvon  ...       Singular   

    White Blood cell count (thousand per microliter)  Blood test result  \
8                                           6.669552  slightly abnormal   
9                                           6.397702           abnormal   
12                                          7.995115  slightly abnormal   
14                                          3.000000  slightly abnormal   
18                                          9.382407           abnormal   

   Symptom 1 Symptom 2 Symptom 3 Symptom 4  Symptom 5  \
8        1.0       1.0       1.0       0.0        1.0   
9        0.0       0.0       1.0       1.0        1.0   
12       1.0       1.0       0.0       1.0        0.0   
14       1.0       0.0       1.0       0.0        1.0   
18       1.0       1.0       0.0       0.0        0.0   

                                Genetic Disorder       Disorder Subclass  
8    Mitochondrial genetic inheritance disorders          Leigh syndrome  
9   Multifactorial genetic inheritance disorders                Diabetes  
12   Mitochondrial genetic inheritance disorders          Leigh syndrome  
14   Mitochondrial genetic inheritance disorders          Leigh syndrome  
18   Mitochondrial genetic inheritance disorders  Mitochondrial myopathy  

[5 rows x 45 columns]

In [55]:
df_train.drop(["Patient Id"], axis = 1, inplace = True)

In [96]:
from sklearn.metrics import accuracy_score
import category_encoders as ce
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import category_encoders as ce
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
print("lib loaded")

lib loaded


In [101]:
X = df_train.drop(['Genetic Disorder', 'Disorder Subclass'], axis =1)
y1 = df_train['Genetic Disorder']
y2 = df_train['Disorder Subclass']

In [122]:
encoder1 = LabelEncoder()
encoder2 = LabelEncoder()
y1 = encoder1.fit_transform(y1)
y2 = encoder2.fit_transform(y2)

binary_encoder_pipeline = Pipeline(steps = [
    ('bin', ce.BinaryEncoder())
])

ordinal_encoder_pipeline = Pipeline(steps = [
    ('ordinal', ce.ordinal.OrdinalEncoder())
])

In [129]:
binary_categorical_columns = [var for var in X.columns if (
    X[var].dtype == 'O' and len(X[var].unique()) == 2
)]
ordinal_categorical_columns = [var for var in X.columns if (
    X[var].dtype == 'O' and var not in binary_categorical_columns
)]



In [141]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import *
from sklearn.metrics import confusion_matrix

In [133]:
preprocessor = ColumnTransformer(transformers = [
    ('cat1', binary_encoder_pipeline, binary_categorical_columns),
    ('cat2', ordinal_encoder_pipeline, ordinal_categorical_columns)
])

In [209]:
def printMetrics(pred, actual):
    print ('Accuracy is {}'.format(accuracy_score(actual, pred)))
    print ('Precision is {}'.format(precision_score(actual, pred, average = "weighted")))
    print ('Recall is {}'.format(recall_score(actual, pred, average = "weighted")))
    print ('F1-Score is {}'.format(f1_score(actual, pred, average = "weighted")))
    print('Confusion Matrix : \n' + str(confusion_matrix(actual,pred)))

def fitModel (model, X, y, params):
    X_train, X_valid, y_train, y_valid = train_test_split(
        X, y, train_size = 0.77, random_state = 10
    )
    finalModel = Pipeline(steps = [
        ('preprocessor', preprocessor),
        ('model', model)
    ])

    clf = GridSearchCV(finalModel, params, n_jobs = -1)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_valid)
    printMetrics(y_pred, y_valid)
    return clf.best_params_
    

In [242]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [201]:
estimators = [
    ('RandomForestClassifier', RandomForestClassifier()),
    ('BaggingClassifier', BaggingClassifier()),
    ('DecisionTreeClassifier', DecisionTreeClassifier()),
    ('ExtraTreeClassifier', ExtraTreesClassifier()),
    ('NaiveBayes', GaussianNB())
]
final_estimator = GradientBoostingClassifier(
  n_estimators=25, subsample=0.5, min_samples_leaf=25, max_features=1,random_state=42
)

In [243]:
X_train, X_valid, y_train, y_valid = train_test_split(
        X, y2, train_size = 0.75, random_state = 32
    )
model = KNeighborsClassifier()
dummyModel = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', model)
])

dummyModel.fit(X_train, y_train)
y_pred = dummyModel.predict(X_valid)
printMetrics(y_pred, y_valid)


Accuracy is 0.1735241502683363
Precision is 0.1627341751423978
Recall is 0.1735241502683363
F1-Score is 0.15930437987579263
Confusion Matrix : 
[[  0   0   2   0   0   0   4   2   2]
 [  0   0   2   0   0   0   2   3   0]
 [  0   1 109  24  24   0  64  31  30]
 [  0   0  57  12  16   0  38  24  22]
 [  0   0  41   8   7   0  34  17  10]
 [  0   0  17   5   7   0  11  10   6]
 [  1   0 141  34  34   1 108  43  57]
 [  3   2 129  31  35   0  94  37  32]
 [  1   0  82  24  26   0  68  34  18]]


In [234]:
params = {
 'model__max_depth': [10, 20, 30, 40, 50, None],
 'model__max_features': ['auto', 'sqrt'],
 'model__min_samples_leaf': [1, 2, 4],
 'model__min_samples_split': [2, 5, 10],
 'model__n_estimators': [100, 200, 300]}
print (fitModel(RandomForestClassifier(), X, y2, params))

Accuracy is 0.24044069993519118
Precision is 0.22132046013621343
Recall is 0.24044069993519118
F1-Score is 0.18889473893781678
Confusion Matrix : 
[[  0   0   5   1   0   0  10   1   0]
 [  0   0   0   0   0   0   3   1   2]
 [  0   0  39   3   0   0 149  74   7]
 [  0   0  20   2   0   0  79  33   1]
 [  0   0   1   0   0   0  50  46   4]
 [  0   0  19   0   0   0  27  12   0]
 [  0   0  46   0   0   0 203 120   9]
 [  0   0  31   0   0   0 183 116   7]
 [  0   0  13   0   0   0 115 100  11]]
{'model__max_depth': 50, 'model__max_features': 'auto', 'model__min_samples_leaf': 4, 'model__min_samples_split': 10, 'model__n_estimators': 100}


RandomForestClassifier

{'model__max_depth': 50, 'model__max_features': 'sqrt', 'model__min_samples_leaf': 4, 'model__min_samples_split': 10, 'model__n_estimators': 200}

In [229]:
print (len(X_train.columns), len(X.columns))


42 42


In [231]:
id = df_test["Patient Id"]
df_test.drop("Patient Id", axis = 1, inplace = True)

In [232]:
finalmodel = RandomForestClassifier(max_depth =  50, max_features =  'sqrt', min_samples_leaf=  4,min_samples_split =  10, n_estimators = 200)
finalPipeline = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', finalmodel)
])
finalPipeline.fit(X, y1)
y1_pred = finalPipeline.predict(df_test)

In [244]:
finalmodel2 = RandomForestClassifier(max_depth =  50, max_features =  'sqrt', min_samples_leaf=  4,min_samples_split =  10, n_estimators = 100)
finalPipeline = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', finalmodel2)
])
finalPipeline.fit(X, y2)
y2_pred = finalPipeline.predict(df_test)

In [245]:
temp.columns

Index(['Patient Id', 'Patient Age', 'Genes in mother's side',
       'Inherited from father', 'Maternal gene', 'Paternal gene',
       'Blood cell count (mcL)', 'Patient First Name', 'Family Name',
       'Father's name', 'Mother's age', 'Father's age', 'Institute Name',
       'Location of Institute', 'Status', 'Respiratory Rate (breaths/min)',
       'Heart Rate (rates/min', 'Test 1', 'Test 2', 'Test 3', 'Test 4',
       'Test 5', 'Parental consent', 'Follow-up', 'Gender', 'Birth asphyxia',
       'Autopsy shows birth defect (if applicable)', 'Place of birth',
       'Folic acid details (peri-conceptional)',
       'H/O serious maternal illness', 'H/O radiation exposure (x-ray)',
       'H/O substance abuse', 'Assisted conception IVF/ART',
       'History of anomalies in previous pregnancies',
       'No. of previous abortion', 'Birth defects',
       'White Blood cell count (thousand per microliter)', 'Blood test result',
       'Symptom 1', 'Symptom 2', 'Symptom 3', 'Symptom 4', 'S

In [253]:
y1_pred = encoder1.inverse_transform(y1_pred)
y2_pred = encoder2.inverse_transform(y2_pred)
result = {
    'Patient Id' : id.tolist(),
    'Genetic Disorder' : y1_pred.tolist(),
    'Disorder Subclass' : y2_pred.tolist(),
}

In [254]:
res = pd.DataFrame(result)

In [255]:
res.to_csv('Submission1.0.csv', index = False)

In [258]:
res.describe()

Patient Id                             Genetic Disorder  \
count        9465                                         9465   
unique       9465                                            2   
top     PID0x4175  Mitochondrial genetic inheritance disorders   
freq            1                                         8771   

       Disorder Subclass  
count               9465  
unique                 6  
top       Leigh syndrome  
freq                7010